apiVersion: v1
kind: Service
metadata:
  name: apache-service 
spec:
  selector:
    app: apache-app # The service looks for pods with this label. 
  ports:
  - port: 8080 # Service Listens to this port.
    targetPort: 80 # Forwards the traffic to this port on any pod with "app=apache-app" label.
  type: LoadBalancer
